---
language: python

python:
  - "3.7"

services:
  - docker

env:
  matrix:
    - image="docker-alpine-openrc"
    - image="docker-alpine-openrc" tag="edge"
    # - namespace="archlinux/" image="base"
    - image="docker-debian-systemd" tag="stable"
    - image="docker-debian-systemd" tag="unstable"
    - image="docker-debian-systemd"
    - image="docker-centos-systemd" tag="7"
    - image="docker-redhat-systemd" tag="7"
    - image="docker-centos-systemd"
    - image="docker-redhat-systemd"
    - image="docker-fedora-systemd"
    - image="docker-fedora-systemd" tag="rawhide"
    - image="docker-opensuse-systemd"
    - image="docker-ubuntu-systemd" tag="rolling"
    - image="docker-ubuntu-systemd" tag="devel"
    - image="docker-ubuntu-systemd"

matrix:
  allow_failures:
    - env: image="docker-alpine-openrc" tag="edge"
    - env: image="docker-debian-systemd" tag="unstable"
    - env: image="docker-fedora-systemd" tag="rawhide"
    - env: image="docker-ubuntu-systemd" tag="rolling"
    - env: image="docker-ubuntu-systemd" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "# out of `travis encrypt robertdebock:TOKEN-FROM-SLACK`"
  email: false
