---

- name: ensure /etc/openvpn/client exists
  ansible.builtin.file:
    path: /etc/openvpn/client
    state: directory
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0750"

- name: place client.conf
  ansible.builtin.template:
    src: client.conf.j2
    dest: "{{ openvpn_configuration_directory }}/client.conf"
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0640"
  notify:
    - restart openvpn
